# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import game_pb2 as game__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in game_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GameServiceStub(object):
    """Service definition for the Distributed Maze Game
    Định nghĩa các hàm RPC mà Client có thể gọi lên Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Join = channel.unary_unary(
                '/maze_game.GameService/Join',
                request_serializer=game__pb2.JoinRequest.SerializeToString,
                response_deserializer=game__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.Move = channel.unary_unary(
                '/maze_game.GameService/Move',
                request_serializer=game__pb2.MoveRequest.SerializeToString,
                response_deserializer=game__pb2.MoveResponse.FromString,
                _registered_method=True)
        self.Shoot = channel.unary_unary(
                '/maze_game.GameService/Shoot',
                request_serializer=game__pb2.ShootRequest.SerializeToString,
                response_deserializer=game__pb2.ShootResponse.FromString,
                _registered_method=True)
        self.Leave = channel.unary_unary(
                '/maze_game.GameService/Leave',
                request_serializer=game__pb2.LeaveRequest.SerializeToString,
                response_deserializer=game__pb2.LeaveResponse.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_stream(
                '/maze_game.GameService/GetGameState',
                request_serializer=game__pb2.GameStateRequest.SerializeToString,
                response_deserializer=game__pb2.GameState.FromString,
                _registered_method=True)


class GameServiceServicer(object):
    """Service definition for the Distributed Maze Game
    Định nghĩa các hàm RPC mà Client có thể gọi lên Server
    """

    def Join(self, request, context):
        """Người chơi tham gia game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Move(self, request, context):
        """Gửi lệnh di chuyển (Input)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shoot(self, request, context):
        """Gửi lệnh bắn đạn
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leave(self, request, context):
        """Người chơi chủ động thoát game
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """Luồng dữ liệu trạng thái game (Global State Streaming)
        Server sẽ gửi liên tục cập nhật về cho Client
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Join': grpc.unary_unary_rpc_method_handler(
                    servicer.Join,
                    request_deserializer=game__pb2.JoinRequest.FromString,
                    response_serializer=game__pb2.JoinResponse.SerializeToString,
            ),
            'Move': grpc.unary_unary_rpc_method_handler(
                    servicer.Move,
                    request_deserializer=game__pb2.MoveRequest.FromString,
                    response_serializer=game__pb2.MoveResponse.SerializeToString,
            ),
            'Shoot': grpc.unary_unary_rpc_method_handler(
                    servicer.Shoot,
                    request_deserializer=game__pb2.ShootRequest.FromString,
                    response_serializer=game__pb2.ShootResponse.SerializeToString,
            ),
            'Leave': grpc.unary_unary_rpc_method_handler(
                    servicer.Leave,
                    request_deserializer=game__pb2.LeaveRequest.FromString,
                    response_serializer=game__pb2.LeaveResponse.SerializeToString,
            ),
            'GetGameState': grpc.unary_stream_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=game__pb2.GameStateRequest.FromString,
                    response_serializer=game__pb2.GameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maze_game.GameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maze_game.GameService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GameService(object):
    """Service definition for the Distributed Maze Game
    Định nghĩa các hàm RPC mà Client có thể gọi lên Server
    """

    @staticmethod
    def Join(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maze_game.GameService/Join',
            game__pb2.JoinRequest.SerializeToString,
            game__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Move(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maze_game.GameService/Move',
            game__pb2.MoveRequest.SerializeToString,
            game__pb2.MoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shoot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maze_game.GameService/Shoot',
            game__pb2.ShootRequest.SerializeToString,
            game__pb2.ShootResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Leave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maze_game.GameService/Leave',
            game__pb2.LeaveRequest.SerializeToString,
            game__pb2.LeaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/maze_game.GameService/GetGameState',
            game__pb2.GameStateRequest.SerializeToString,
            game__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
